version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest tests/test_data_loading.py tests/test_data_cleaning.py tests/test_data_analysis.py
workflows:
  version: 2
  test:
    jobs:
      - build
