version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Data Analysis
          command: python scripts/data_analysis.py
      - run:
          name: Run Pytest
          command: pytest

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
