version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s data/tests -p "test_*.py"

workflows:
  version: 2
  test:
    jobs:
      - build
