version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
            
       - run:
          name: Run Data analysis
          command: python data_analysis.py
            
      - run:
          name: Run Pytest
          command: ~/.local/bin/pytest 

workflows:
  version: 2
  test:
    jobs:
      - build
